Increasing test coverage and configuring travis.yml for poi density api
niels89/EloquentElks pull request #34
Opened 2021-05-17 08:04 UTC by saurabhprasun20

Travis.yml for POI density api and added a unit test for repo in airbnb api

2021-05-17 09:08 UTC, niels89 requested changes
LGTM, please make sure to revert the changes in .travis.yml, as this is already present on develop

2021-05-17 09:08 UTC, niels89 commented on .travis.yml
> +            - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm --prefix ./eloquent-elks-poi-density-api coveralls
POI Density API is already integrated into Travis CI on develop, so this can be reverted to how it was before.

2021-05-18 19:03 UTC, saurabhprasun20 commented on .travis.yml
> +            - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm --prefix ./eloquent-elks-poi-density-api coveralls
Removed

2021-05-20 07:21 UTC, niels89 approved these changes

2021-05-20 20:11 UTC, merged